name = "Create VC"
author = "Jammersmurph"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de916695b11d263f7a90374bc262ae2a8bf4f026ae3dd3511c07cfe9b18b2632"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.224"
