name = "Create VC"
author = "Jammersmurph"
version = "Auto Update"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b66f55884728be0e1c760ff646e291c55868c5daca5d9d92a37681bf58126c3b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
