name = "Create VC"
author = "Jammersmurph"
version = "Auto Update"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da2db39f6c5e47ecf0b2d09dbb997958c1ff71f6dde333507ac8ff0cf687ce44"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
